server:
  port: 12581
  servlet:
    session:
      timeout: 30m

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xx_s?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root


Logging:
  level:
    com.wms: debug